name: snapchat
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.16.1 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^10.1.0
  camera: ^0.9.4+21
  path_provider: ^2.0.9
  path: ^1.8.0
  flutter_map: ^0.14.0
  geolocator: ^8.2.0
  geocoding: ^2.0.4
  video_player: ^2.4.0
  cupertino_icons: ^1.0.4
  latlong2: ^0.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  ios: true
  android: true
  image_path_ios: "assets/icon.png"
  image_path_android: "assets/icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
    - assets/avatar.jpg
    - assets/avatar-friends.jpg
    - assets/friend-1.png
    - assets/friend-2.jpg
    - assets/friend-story-1.jpg
    - assets/friend-story-2.jpg
    - assets/subscriptions-1.jpg
    - assets/subscriptions-2.jpg
    - assets/discover-1.jpg
    - assets/discover-2.jpg
    - assets/spotlight-account-icon.jpg
    - assets/spotlight-video.mp4
    - assets/snapcode.png
    - assets/bitmoji-friends.png
    - assets/snapchat-logo-setting.png
    - assets/search-game-1.png
    - assets/search-game-2.png
    - assets/search-trend-img-account-1.jpg
    - assets/search-trend-img-account-2.jpg

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
